### ISSUE TITLE
Diseño del panel de administración [#3: Registrar producto]

### ISSUE THREAD

**Issue by Pathyfernandez** [Pololiis/proyectoIntegrador#10]
Diseñar un panel de administración que incluya un botón claramente identificable para agregar productos nuevos

**Comment by Yoryao** [comment]
El producto debe visualizarse en el listado de productos. (Relacionada con historia #4)
El panel de administración debe contener un botón  "Agregar producto".
La página de "Agregar producto" debe incluir campos para ingresar información relevante del producto, como nombre, descripción e imagen.
Se debe poder subir una o más imágenes del producto.
Se debe poder guardar el producto y este debe ser agregado correctamente a la base de datos del sitio.
Si se intenta agregar un producto con un nombre que ya existe, se debe mostrar un mensaje de error indicando que el nombre ya está en uso.
