### ISSUE TITLE
Desarrollo de la página "Agregar producto" [#3: Registrar producto]

### ISSUE THREAD

**Issue by Pathyfernandez** [Pololiis/proyectoIntegrador#13]
Desarrollar la funcionalidad de la página "Agregar producto" para permitir al administrador ingresar la información del producto y subir una o más imágenes.

**Comment by luisoce** [comment]
-     **Crear un endpoint API para agregar productos**: Este endpoint debe recibir los datos del formulario de registro del producto (nombre, descripción, imágenes, entre otros) y almacenarlos en la base de datos. 
-     **Notificar al usuario (éxito o error del registro)**: Se debera mostrar un mensaje al usuario indicando si el producto se ha agregado correctamente o si ha ocurrido algún error durante el proceso.
