### ISSUE TITLE
Implementación de la validación del nombre del producto [#3: Registrar producto]

### ISSUE THREAD

**Issue by Pathyfernandez** [Pololiis/proyectoIntegrador#14]
1. Implementar la validación para asegurar que no se pueda agregar un producto con un nombre que ya existe en la base de datos.
2. Mostrar un mensaje de error claro si se intenta agregar un producto con un nombre que ya está en uso

**Comment by luisoce** [comment]
• **Crear un endpoint API para agregar productos**: Este endpoint debe recibir los datos del formulario de registro del producto (nombre, descripción, imágenes, entre otros) y almacenarlos en la base de datos. 
    • **Notificar al usuario (éxito o error del registro)**: Se debera mostrar un mensaje al usuario indicando si el producto se ha agregado correctamente o si ha ocurrido algún error durante el proceso.

**Comment by luisoce** [comment]
- **Validar la unicidad del nombre del producto**: Antes de guardar el producto, se debe verificar si ya existe otro producto con el mismo nombre en la base de datos. Si se encuentra un producto duplicado, se debe retornar un error al usuario.
