### ISSUE TITLE
Selección aleatoria de productos [#4: Visualizar productos en el home]

### ISSUE THREAD

**Issue by Pathyfernandez** [Pololiis/proyectoIntegrador#17]
1. Desarrollar un algoritmo que seleccione hasta 10 productos aleatorios de la base de datos para mostrar en el home.
2. Garantizar que no se seleccionen productos repetidos y que la selección sea verdaderamente aleatoria.

**Comment by luisoce** [comment]
- **Enviar la lista de productos al frontend**: El endpoint API debe enviar la lista de productos aleatorios al frontend en un formato JSON adecuado para que pueda ser procesado y mostrado en la página.
