### ISSUE TITLE
Desarrollo de la funcionalidad de acceso a todas las imágenes  [#5: Visualizar detalle de producto]

### ISSUE THREAD

**Issue by Pathyfernandez** [Pololiis/proyectoIntegrador#23]
1. Desarrollar la funcionalidad para que al hacer clic en "Ver más", se abra un componente o modal que muestre todas las imágenes disponibles del producto

**Comment by luisoce** [comment]
-     **Endpoint API para obtener el detalle del producto**: El endpoint debe recibir como parámetro el ID del producto y retornar la información detallada del producto, incluyendo título, descripción, imágenes, etc. 
-     **Consumir el endpoint API en el frontend**: Utilizar una biblioteca HTTP como Axios para realizar una solicitud GET al endpoint API creado en el paso 1, pasando como parámetro el ID del producto seleccionado. 
-     **Procesar la respuesta del backend**: En el frontend, recibir la respuesta JSON del endpoint API y procesarla para extraer la información detallada del producto. 
-     **Mostrar la información del producto en la página**: Utilizar técnicas de HTML y CSS para crear una estructura adecuada para mostrar el título, la descripción y las imágenes del producto.
