### ISSUE TITLE
US #13: Registrar usuario

### ISSUE THREAD

**Issue by Yoryao** [Pololiis/proyectoIntegrador#35]

**Comment by Yoryao** [comment]
Como usuario anónimo, quiero poder registrarme en el sitio para poder acceder a funcionalidades extras.

- [x] Proporcionar información precisa y válida durante el proceso de registro, como nombre, apellido, dirección de correo electrónico, contraseña.
- [x] Validar que los campos de nombre, apellido, la dirección de correo electrónico  y contraseña del usuario cumplan con reglas para prevenir errores en los datos proporcionados.
- [x] Proporcionar una experiencia de usuario intuitiva y fácil de usar durante todo el proceso de registro.

**Comment by Pathyfernandez** [comment]
falta correo con envio de confirmacion de creacion de Usuario
