### ISSUE TITLE
US #14: Identificar usuario

### ISSUE THREAD

**Issue by Yoryao** [Pololiis/proyectoIntegrador#36]

**Comment by Yoryao** [comment]
Como usuario, quiero poder iniciar sesión en mi cuenta para acceder a información personal y realizar reservas de manera más fácil.

- [x] Iniciar sesión en la cuenta del usuario utilizando una dirección de correo electrónico y una contraseña válidas.
- [x] Mostrar un mensaje de error claro y útil en caso de que el usuario proporcione información de inicio de sesión incorrecta.
- [x] Permitir al usuario acceder a la información personal y las funcionalidades disponibles después de iniciar sesión.
- [x] Cuando el usuario está identificado mostrar su nombre, un avatar de letras con las iniciales del nombre de usuario.

**Comment by Pathyfernandez** [comment]
A la espera de Backend.. para cierre
